import {SCENES,EVIDENCE,endingFor,validateState} from './story.mjs';

const $=s=>document.querySelector(s), app=$('#app'), modal=$('#modal'), toast=$('#toast');
const KEY='future-signal-state-v1';
let state=loadState()||{version:1,scene:'wake',ending:null,history:[],evidence:[],started:false};
let audioOn=false, audioCtx=null, ambience=null;

function loadState(){try{return validateState(JSON.parse(localStorage.getItem(KEY)))}catch{return null}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function showToast(msg){toast.textContent=msg;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2600)}
function ensureAudio(){if(!audioCtx)audioCtx=new (window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume();return audioCtx}
function buzz(){if(!audioOn)return;const ctx=ensureAudio(),o=ctx.createOscillator(),g=ctx.createGain();o.frequency.value=220;o.type='sine';g.gain.setValueAtTime(.035,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.13);o.connect(g).connect(ctx.destination);o.start();o.stop(ctx.currentTime+.13)}
function startAmbience(){const ctx=ensureAudio();if(ambience)return;const master=ctx.createGain();master.gain.setValueAtTime(0,ctx.currentTime);master.gain.linearRampToValueAtTime(.055,ctx.currentTime+2.4);master.connect(ctx.destination);const nodes=[];[[55,'sine',.32],[82.41,'sine',.13],[164.81,'triangle',.035]].forEach(([frequency,type,volume])=>{const o=ctx.createOscillator(),g=ctx.createGain();o.type=type;o.frequency.value=frequency;g.gain.value=volume;o.connect(g).connect(master);o.start();nodes.push(o)});const lfo=ctx.createOscillator(),lfoGain=ctx.createGain();lfo.frequency.value=.075;lfoGain.gain.value=3;lfo.connect(lfoGain);lfoGain.connect(nodes[1].detune);lfo.start();nodes.push(lfo);const pulse=ctx.createOscillator(),pulseGain=ctx.createGain();pulse.type='sine';pulse.frequency.value=1.5;pulseGain.gain.value=.012;pulse.connect(pulseGain).connect(master);pulse.start();nodes.push(pulse);ambience={master,nodes}}
function stopAmbience(){if(!ambience||!audioCtx)return;const current=ambience;ambience=null;current.master.gain.cancelScheduledValues(audioCtx.currentTime);current.master.gain.setValueAtTime(current.master.gain.value,audioCtx.currentTime);current.master.gain.linearRampToValueAtTime(0,audioCtx.currentTime+1.2);setTimeout(()=>current.nodes.forEach(node=>{try{node.stop()}catch{}}),1300)}

function landing(){
 app.innerHTML=`<section class="hero"><div class="hero-copy"><div class="eyebrow">CASE FILE / 01 · INTERACTIVE ANTI-FRAUD</div><h1>你会相信<br><em>十分钟后的你</em>吗？</h1><p class="hero-intro">一条来自未来的消息，<br>一场还没有发生的骗局。<br><strong>你的每一个选择，都会改写结局。</strong></p><div class="meta-chips"><span><i>◉</i> 悬疑叙事</span><span><i>◌</i> 约 5 分钟</span></div><div class="hero-actions"><button class="primary" id="start">开始调查 <span class="arrow">↗</span></button><button class="secondary" id="continue" ${state.history.length?'':'hidden'}>继续上次调查</button></div><p class="start-note">虚构情境 · 不涉及真实交易 · 可随时退出</p></div><div class="hero-art"><div class="orbit"><span class="orbit-tick">SIGNAL / 21:50:07</span></div><div class="big-time">21:50</div><div class="signal-card"><small>INCOMING / FROM YOURSELF</small><p>不要付第二笔钱。<br><span>— 十分钟后的你</span></p></div><div class="phone"><div class="phone-screen"><div class="phone-island"></div><div class="phone-status"><span>21:40</span><span>▮▮▮ ◇</span></div><div class="lock-date">星期五 · 10月24日</div><div class="lock-time">21:40</div><div class="notification"><header><b>↗ 未来来信</b><span>刚刚</span></header><strong>你有一条来自未来的消息</strong><p>先别付第二笔钱。<br>我知道你刚刚付了 199 元订金...</p></div><div class="phone-bottom">向上滑动以调查</div></div></div><div class="warning-card"><small>WARNING / 02</small><p>你还剩 <b>10:00</b><br>改变这一切。</p></div><div class="art-coordinate">40°N 116°E / SIGNAL LOCKED</div></div></section><section class="intro-strip"><div class="intro-item"><span class="intro-number">01</span><div><h3>像真实聊天一样调查</h3><p>没有标准答案，只有你的判断。</p></div><span class="intro-icon">⌁</span></div><div class="intro-item"><span class="intro-number">02</span><div><h3>打开证据，找到破绽</h3><p>每份材料都藏着一个问题。</p></div><span class="intro-icon">▧</span></div><div class="intro-item"><span class="intro-number">03</span><div><h3>结局复盘每一步</h3><p>把“感觉不对”变成可验证。</p></div><span class="intro-icon">✦</span></div></section>`;
 $('#start').onclick=()=>{state={version:1,scene:'wake',ending:null,history:[],evidence:[],started:true};save();renderScene()};
 $('#continue')?.addEventListener('click',renderScene);
}

function renderScene(){
 const scene=SCENES[state.scene]; if(!scene){renderEnding();return}
 const seen=state.history.length, active=Math.min(seen+1,5);
 app.innerHTML=`<div class="game-wrap"><div class="game-top"><button class="back" id="quit">← 返回首页</button><span class="chapter-label">CHAPTER ${scene.chapter} / ${esc(scene.name.toUpperCase())}</span><button class="restart-link" id="restart">重新开始</button></div><div class="game-grid"><section class="chat-panel"><header class="chat-head"><div class="avatar ${scene.kind}">${esc(scene.avatar)}</div><div><h2>${esc(scene.speaker)}</h2><small>${esc(scene.signal)}</small></div><span class="chat-clock">${esc(scene.time)}</span></header><div class="chat-content"><div class="scene-divider">— ${scene.kind==='future'?'未知来源 / 加密消息':'消息记录'} —</div>${scene.messages.map(x=>`<div class="bubble ${scene.kind}">${esc(x)}</div>`).join('')}${scene.attachment?attachmentButton(scene.attachment):''}<p class="narration">${esc(scene.narration)}</p>${scene.future?`<div class="future-whisper"><small>来自十分钟后的你 / 语音转文字</small>${esc(scene.future)}</div>`:''}</div><div class="choices"><div class="choice-heading"><span>你会怎么做？</span><span>选择会影响时间线</span></div>${scene.choices.map((c,i)=>`<button class="choice" data-choice="${c.id}"><span class="choice-letter">${String.fromCharCode(65+i)}</span><span><strong>${esc(c.text)}</strong><small>${esc(c.sub)}</small></span><span class="choice-arrow">→</span></button>`).join('')}</div></section><aside class="game-sidebar"><section class="side-panel progress-panel"><div class="side-heading"><h3>时间线</h3><span>${String(active).padStart(2,'0')} / 05</span></div><div class="timeline">${[1,2,3,4,5].map(i=>`<i class="${i<=active?'active':''}"></i>`).join('')}</div><p class="side-description">你的调查正在改变未来。先暂停，再核实，最后决定。</p></section><section class="side-panel evidence-panel"><div class="side-heading"><h3>证据档案</h3><span>${String(state.evidence.length).padStart(2,'0')} FOUND</span></div><div>${EVIDENCE.map(e=>`<button class="evidence-button" data-evidence="${e.id}"><span class="file-num">${e.number}</span><span><strong>${esc(e.name)}</strong><small>${esc(e.type)}</small></span><span class="file-state">${state.evidence.includes(e.id)?'已查看':'未打开'}</span></button>`).join('')}</div></section></aside></div></div>`;
 $('#quit').onclick=landing;$('#restart').onclick=()=>{state={version:1,scene:'wake',ending:null,history:[],evidence:[],started:true};save();renderScene()};
 app.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>choose(b.dataset.choice));app.querySelectorAll('[data-evidence]').forEach(b=>b.onclick=()=>openEvidence(b.dataset.evidence));
}
function attachmentButton(id){const e=EVIDENCE.find(x=>x.id===id);return `<button class="attachment" data-evidence="${id}"><span class="attachment-icon">▧</span><span><strong>${esc(e.name)}</strong><small>${esc(e.type)} · 点击查看</small></span><span>↗</span></button>`}
function choose(id){const scene=SCENES[state.scene], choice=scene.choices.find(x=>x.id===id);if(!choice)return;buzz();state.history.push({scene:state.scene,choice:id});if(choice.openEvidence&&!state.evidence.includes(scene.attachment))state.evidence.push(scene.attachment);if(choice.ending)state.ending=choice.ending;else state.scene=choice.next;save();if(choice.feedback)showToast(choice.feedback);setTimeout(()=>state.ending?renderEnding():renderScene(),300)}
function openEvidence(id){const e=EVIDENCE.find(x=>x.id===id);if(!e)return;if(!state.evidence.includes(id)){state.evidence.push(id);save()}modal.innerHTML=`<div class="modal-inner"><button class="modal-close" aria-label="关闭">×</button><div class="modal-kicker">EVIDENCE / ${e.number} · ${esc(e.type.toUpperCase())}</div><h2>${esc(e.name)}</h2><div class="exhibit"><span class="specimen">CASE 24-10 / SIMULATION</span><h3>${esc(e.title)}</h3><h4>${esc(e.subtitle)}</h4><p>${esc(e.body)}</p><small>${esc(e.note)}</small>${id==='ticket'?'<div class="barcode"></div>':''}</div><button class="hotspot">⌁ 先猜一猜：${esc(e.hotspot)}</button><div class="finding"><strong>调查发现 / ${esc(e.label)}</strong><p>${esc(e.finding)}</p></div><p class="modal-caption">证据用于虚构情境演示。现实中请通过自己找到的官方渠道核实。</p></div>`;modal.showModal();modal.querySelector('.modal-close').onclick=()=>modal.close()}
 function renderEnding(){const end=endingFor(state.ending), rows=state.history.map((r,i)=>{const s=SCENES[r.scene],c=s.choices.find(x=>x.id===r.choice);return `<div class="review-row"><small>STEP ${String(i+1).padStart(2,'0')} / ${esc(s.name)}</small><h4>${esc(c.text)}</h4><p>${esc(c.feedback||'')}</p></div>`}).join('');app.innerHTML=`<div class="end-wrap ${end.color==='pink'?'pink':''}"><section class="end-hero"><div class="end-symbol">${end.color==='pink'?'↻':'✓'}</div><div class="eyebrow">${esc(end.label.toUpperCase())}</div><h1>${esc(end.title)}</h1><p class="end-subtitle">${esc(end.subtitle)}</p><p class="end-description">${esc(end.message)}</p></section><div class="end-grid"><section class="review-panel"><div class="side-heading"><h3>你的调查复盘</h3><span>${state.history.length} STEPS</span></div>${rows||'<p class="side-description">你还没有做出选择。</p>'}</section><section class="actions-panel"><div class="side-heading"><h3>现实中的下一步</h3><span>KEEP THIS</span></div><ol class="action-list"><li>停止继续转账，不为解冻、退款或追款再付钱。</li><li>保存聊天、链接、账号、订单和转账记录。</li><li>通过自己找到的官方渠道、银行或 110 求助核实。</li></ol></section></div><div class="end-buttons"><button class="primary" id="again">再调查一次 <span class="arrow">↗</span></button><button class="secondary" id="share">复制我的调查结果</button></div><p class="download-note">把这次判断带回现实：越催你立刻决定，越要先暂停、再核实。</p></div>`;$('#again').onclick=()=>{state={version:1,scene:'wake',ending:null,history:[],evidence:[],started:true};save();renderScene()};$('#share').onclick=share}
 async function share(){const text=`《十分钟后的你》\n${endingFor(state.ending).title}\n我在 ${state.history.length} 个关键节点做出了选择。\n反诈提醒：先暂停，再核实。`;try{await navigator.clipboard.writeText(text);showToast('调查结果已复制，可以发给朋友一起体验。')}catch{showToast('复制失败，请手动截图分享。')}}
 $('#sound-toggle').onclick=()=>{$('#sound-toggle').setAttribute('aria-pressed',String(audioOn=!audioOn));$('#sound-toggle span').textContent=audioOn?'声音开':'声音关';if(audioOn){startAmbience();buzz()}else stopAmbience()};$('#about-button').onclick=()=>{modal.innerHTML=`<div class="modal-inner"><button class="modal-close" aria-label="关闭">×</button><div class="modal-kicker">ABOUT THE EXPERIENCE</div><h2>一条消息，改变一次判断。</h2><p>《十分钟后的你》是一款悬疑叙事式反诈互动 H5。它把“先暂停、再核实、求助”变成一次可以亲手完成的调查。</p><div class="about-grid"><div>悬疑叙事<small>用时间线制造代入感</small></div><div>证据练习<small>从来源和独立渠道核实</small></div><div>AI 陪练<small>把疑问变成可验证的问题</small></div><div>虚构安全<small>无真实链接、无真实付款</small></div></div><p class="modal-caption">参赛作品原型 · FUTURE SIGNAL / 2026</p></div>`;modal.showModal();modal.querySelector('.modal-close').onclick=()=>modal.close()};
 if(state.started&&state.history.length)renderScene();else landing();


